### ISSUE TITLE
Hiddeneye error - how to fix this..?

### ISSUE THREAD

**Issue by CortesWasTaken** [DarkSecDevelopers/HiddenEye-Legacy#853]
I'm getting this certain error when I try to run Hiddeneye using "python3 hiddeneye.py". How do I fix this? I tried running the hiddeneyereborn version too, but I have no clue how to run that version. Any suggestions? I have 0 experience with coding, so it would be really helpful if someone could write down the exact coding for me to fix this. I've been looking for solutions on the internet, but nothing seems to work. Thanks in advance!

![Hiddeneye](https://user-images.githubusercontent.com/72491720/95323853-1d571280-089f-11eb-9605-d0f60172ad32.png)

**Comment by Vanillacxz26** [comment]
Request pull for hiddeneye py. ///

**Comment by Vanillacxz26** [comment]
Python. DDR. hdd 256 bitxxx

**Comment by Vanillacxz26** [comment]
Request pulll

**Comment by Vanillacxz26** [comment]
Use open source linux for coding. Javadcript.

**Comment by Vanillacxz26** [comment]
Beep me up.

**Comment by Vanillacxz26** [comment]
* Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

$ hiddenpyhiddem.
hiddenpyhiddem.: command not found
$ y/m
bash: y/m: No such file or directory

**Comment by kaleb119** [comment]
I'm having the same issue on HIDDEN EYE, once I try using it with ngrok I get this error

Traceback (most recent call last):                                      File "/data/data/com.termux/files/home/HiddenEye-Legacy/HiddenEye.py", line 45, in <module>                                                   server_runner.server_selection(port)                                File "/data/data/com.termux/files/home/HiddenEye-Legacy/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection             NgrokController().establish_connection(port=port)                   File "/data/data/com.termux/files/home/HiddenEye-Legacy/controllers/ngrok_controller.py", line 32, in establish_connection                    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)                                             File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pyngrok/ngrok.py", line 201, in connect                                     if pyngrok_config.config_path is not None:
AttributeError: 'str' object has no attribute 'config_path'

**Comment by himanshumehla** [comment]
please i also have the same issue tell me the solution for that

**Comment by Rashed07c** [comment]
i also have the same issue

**Comment by brian77-git** [comment]
I also have same issue

**Comment by shaddy1976** [comment]
Hi, Im getting this issue while working on hiddeneye. No hands down experience in coding, It would be great if one of you could help me solve this issue completely.
Thanks.

File "HiddenEye.py", line 45, in <module>                                                                                                                                                                                                
    server_runner.server_selection(port)                                                                                                                                                                                                   
  File "/root/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection                                                                                                                                          
    NgrokController().establish_connection(port=port)                                                                                                                                                                                      
  File "/root/HiddenEye/controllers/ngrok_controller.py", line 32, in establish_connection                                                                                                                                                 
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)                                                                                                                                          
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 176, in connect                                                                                                                                                     
    api_url = get_ngrok_process(pyngrok_config).api_url                                                                                                                                                                                    
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process                                                                                                                                           
    ensure_ngrok_installed(pyngrok_config.ngrok_path)                                                                                                                                                                                      
AttributeError: 'str' object has no attribute 'ngrok_path'
