### ISSUE TITLE
ngrok problem

### ISSUE THREAD

**Issue by celebrity2020** [DarkSecDevelopers/HiddenEye-Legacy#860]
**this is the message i get when im trying to use ngrok.... any solution for me pleaseeeee**

Traceback (most recent call last):
  File "HiddenEye.py", line 45, in <module>
    server_runner.server_selection(port)
  File "/home/celebrity/Desktop/newfolder/HiddenEye-Legacy/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection
    NgrokController().establish_connection(port=port)
  File "/home/celebrity/Desktop/newfolder/HiddenEye-Legacy/controllers/ngrok_controller.py", line 32, in establish_connection
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 176, in connect
    api_url = get_ngrok_process(pyngrok_config).api_url
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process
    ensure_ngrok_installed(pyngrok_config.ngrok_path)
AttributeError: 'str' object has no attribute 'ngrok_path'

**Comment by TonicWhisper** [comment]
Yeah, I have the same problem too, please help me fix it.

**Comment by Blacksorceres** [comment]
solucion :
pip install pyngrok

> **this is the message i get when im trying to use ngrok.... any solution for me pleaseeeee**
> 
> Traceback (most recent call last):
> File "HiddenEye.py", line 45, in
> server_runner.server_selection(port)
> File "/home/celebrity/Desktop/newfolder/HiddenEye-Legacy/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection
> NgrokController().establish_connection(port=port)
> File "/home/celebrity/Desktop/newfolder/HiddenEye-Legacy/controllers/ngrok_controller.py", line 32, in establish_connection
> self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 176, in connect
> api_url = get_ngrok_process(pyngrok_config).api_url
> File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process
> ensure_ngrok_installed(pyngrok_config.ngrok_path)
> AttributeError: 'str' object has no attribute 'ngrok_path'

R:// sudo apt install pip
pip install pyngrok
buena suerte.
