### ISSUE TITLE
[BUG] Traceback (most recent call last)

### ISSUE THREAD

**Issue by xbox360colombia** [DarkSecDevelopers/HiddenEye-Legacy#868]
Traceback (most recent call last)
![Screenshot from 2020-11-11 06-25-06](https://user-images.githubusercontent.com/16197568/98837240-bb934680-2410-11eb-91ed-8a8162e4fc1c.png)
:
  File "HiddenEye.py", line 45, in <module>
    server_runner.server_selection(port)
  File "/home/kalilinux/scripts/HiddenEye-Legacy/Defs/ActionManager/Server/server_runner.py", line 64, in server_selection
    NgrokController().establish_connection(port=port)
  File "/home/kalilinux/scripts/HiddenEye-Legacy/controllers/ngrok_controller.py", line 32, in establish_connection
    self._model.connect(port=port, name='HiddenEye Connection', pyngrok_config=self._config_path)
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 176, in connect
    api_url = get_ngrok_process(pyngrok_config).api_url
  File "/usr/local/lib/python3.8/dist-packages/pyngrok/ngrok.py", line 126, in get_ngrok_process
    ensure_ngrok_installed(pyngrok_config.ngrok_path)
AttributeError: 'str' object has no attribute 'ngrok_path'

**Comment by prasanth-star** [comment]
bro i also have this problem pls help me sir please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please
